(module
  (type $FUNCSIG$iii (func (param i32 i32) (result i32)))
  (type $FUNCSIG$vii (func (param i32 i32)))
  (type $FUNCSIG$v (func))
  (type $FUNCSIG$vi (func (param i32)))
  (import "test" "equals" (func $equals (param i32 i32)))
  (import "env" "loadMessage" (func $loadMessage (param i32 i32)))
  (import "env" "loadMessageCap" (func $loadMessageCap (param i32 i32) (result i32)))
  (import "env" "storeMessage" (func $storeMessage (param i32 i32)))
  (table (export "callbacks") 2 2 anyfunc)
  (elem (i32.const 0) $__wasm_nullptr $loadCb)
  (memory $0 1)
  (export "memory" (memory $0))
  (export "loadCb" (func $loadCb))
  (export "onCreation" (func $onCreation))
  (export "onMessage" (func $onMessage))
  (func $loadCb (type $FUNCSIG$vi) (param $0 i32)
    (call $equals
      (call $loadMessageCap
        (get_local $0)
        (i32.const 0)
      )
      (i32.const 2)
    )
  )
  (func $onCreation (param $0 i32)
    (call $storeMessage
      (i32.const 0)
      (get_local $0)
    )
  )
  (func $onMessage (param $0 i32)
    (call $loadMessage
      (i32.const 0)
      (i32.const 1)
    )
  )
  (func $__wasm_nullptr (type $FUNCSIG$v)
    (unreachable)
  )
)
