(module
 (type $FUNCSIG$vii (func (param i32 i32)))
 (type $FUNCSIG$iiii (func (param i32 i32 i32) (result i32)))
 (type $FUNCSIG$vi (func (param i32)))
 (import "env" "createMessage" (func $createMessage (param i32 i32 i32) (result i32)))
 (import "test" "equals" (func $equals (param i32 i32)))
 (import "env" "respond" (func $respond (param i32)))
 (table 0 anyfunc)
 (memory $0 1)
 (export "memory" (memory $0))
 (export "onCreation" (func $onCreation))
 (func $onCreation (; 3 ;) (param $0 i32)
  (call $equals
   (get_local $0)
   (i32.const 0)
  )
  (call $respond
   (call $createMessage
    (i32.const 0)
    (i32.const 0)
    (i32.const -1)
   )
  )
 )
)
